import type { CSSProperties } from "react";

export const S = {
  page: { fontFamily: "system-ui, sans-serif", maxWidth: 880, margin: "0 auto", padding: 16, color: "#1a1a1a" },
  header: { marginBottom: 16 },
  h1: { fontSize: 22, fontWeight: 600, margin: "0 0 10px" },
  modeWrap: { display: "flex", gap: 8 },
  modeActive: { background: "#185FA5", color: "#fff", padding: "5px 14px", borderRadius: 8, fontSize: 13, fontWeight: 500 },
  modeDisabled: { background: "#F1EFE8", color: "#888780", padding: "5px 14px", borderRadius: 8, fontSize: 13 },
  ioWrap: { display: "flex", gap: 8, marginTop: 10 },
  ioBtn: { display: "flex", alignItems: "center", gap: 5, background: "#fff", border: "1px solid #d3d1c7", color: "#444441", padding: "7px 14px", borderRadius: 8, fontSize: 13, cursor: "pointer" },
  note: { fontSize: 13, color: "#5F5E5A", lineHeight: 1.7, marginBottom: 14 },
  card: { background: "#fff", border: "1px solid #e5e3da", borderRadius: 12, padding: 16, marginBottom: 14 },
  cardTotal: { background: "#F1EFE8", border: "1px solid #d3d1c7", borderRadius: 12, padding: 16, marginBottom: 14, marginTop: 14 },
  lineHead: { fontSize: 15, fontWeight: 600, marginBottom: 12, display: "flex", justifyContent: "space-between", alignItems: "center" },
  appWrap: { display: "flex", gap: 8, flexWrap: "wrap" },
  appBtn: { background: "#fff", border: "1px solid #d3d1c7", color: "#444441", padding: "7px 16px", borderRadius: 8, fontSize: 13, cursor: "pointer" },
  appActive: { background: "#185FA5", border: "1px solid #185FA5", color: "#fff", padding: "7px 16px", borderRadius: 8, fontSize: 13, cursor: "pointer", fontWeight: 500 },
  skillRow: { display: "flex", flexWrap: "wrap", alignItems: "flex-start", gap: 10 },
  skillBlock: { display: "flex", flexDirection: "column", gap: 6, position: "relative", paddingRight: 18 },
  selWrap: { display: "flex", alignItems: "center", gap: 4 },
  select: { padding: "7px 8px", borderRadius: 8, border: "1px solid #d3d1c7", fontSize: 13, minWidth: 130 },
  removeBtnSm: { border: "none", background: "#FCEBEB", color: "#A32D2D", borderRadius: 6, padding: "3px 8px", cursor: "pointer", fontSize: 12, display: "flex", alignItems: "center", gap: 3 },
  removeBtnXs: { border: "none", background: "transparent", color: "#A32D2D", cursor: "pointer", padding: 0, alignSelf: "center" },
  check: { fontSize: 12, color: "#444441", display: "flex", alignItems: "center", gap: 4 },
  checkReq: { fontSize: 12, color: "#185FA5", display: "flex", alignItems: "center", gap: 4 },
  arrow: { position: "absolute", right: -2, top: 8, color: "#888780", fontSize: 16 },
  addBtn: { display: "flex", alignItems: "center", gap: 4, border: "1px dashed #b4b2a9", background: "transparent", color: "#5F5E5A", borderRadius: 8, padding: "8px 12px", cursor: "pointer", fontSize: 13 },
  addBtnSm: { border: "1px dashed #b4b2a9", background: "transparent", color: "#5F5E5A", borderRadius: 8, padding: "6px 10px", cursor: "pointer", fontSize: 12 },
  addRow: { display: "flex", gap: 6, flexWrap: "wrap", marginTop: 10 },
  unitResult: { fontSize: 12, color: "#5F5E5A", marginTop: 8, paddingTop: 8, borderTop: "1px dashed #e5e3da" },
  bonusNote: { fontSize: 12, color: "#0F6E56", marginTop: 8, fontWeight: 500 },
  flowError: { fontSize: 12, color: "#A32D2D", marginTop: 6, fontWeight: 500 },
  seriesBreakdown: { marginTop: 12, padding: 10, background: "#FAFAF8", borderRadius: 8, border: "1px solid #e5e3da" },
  breakdownTitle: { fontSize: 13, fontWeight: 600, marginBottom: 6, color: "#444441" },
  breakdownRow: { display: "flex", justifyContent: "space-between", fontSize: 12, color: "#5F5E5A", padding: "2px 0" },
  breakdownTotal: { display: "flex", justifyContent: "space-between", fontSize: 14, fontWeight: 600, padding: "6px 0 0", marginTop: 6, borderTop: "1px solid #d3d1c7", color: "#1a1a1a" },
  throwTag: { background: "#E1F5EE", color: "#0F6E56", padding: "7px 12px", borderRadius: 8, fontSize: 13, fontWeight: 500 },
  catchTag: { background: "#FAECE7", color: "#993C1D", padding: "7px 12px", borderRadius: 8, fontSize: 13, fontWeight: 500 },
  checkList: { listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 8 },
  checkItem: { display: "flex", alignItems: "center", gap: 10, fontSize: 14 },
  ok: { color: "#0F6E56", fontWeight: 700 },
  ng: { color: "#A32D2D", fontWeight: 700 },
  pending: { color: "#BA7517", fontWeight: 700 },
  okText: { color: "#1a1a1a" },
  ngText: { color: "#A32D2D" },
  missingBox: { marginTop: 12, background: "#FCEBEB", color: "#A32D2D", padding: "8px 12px", borderRadius: 8, fontSize: 13 },
  warnBox: { marginTop: 8, background: "#FAEEDA", color: "#854F0B", padding: "8px 12px", borderRadius: 8, fontSize: 13 },
  totalRow: { display: "flex", justifyContent: "space-between", fontSize: 14, padding: "6px 0", color: "#444441" },
  subtotalRow: { display: "flex", justifyContent: "space-between", fontSize: 14, fontWeight: 600, padding: "6px 0", marginTop: 4, borderTop: "1px dashed #d3d1c7", color: "#1a1a1a" },
  categoryHead: { fontSize: 13, fontWeight: 600, marginTop: 12, marginBottom: 4, color: "#185FA5" },
  grandRow: { display: "flex", justifyContent: "space-between", fontSize: 18, fontWeight: 600, padding: "10px 0 0", marginTop: 6, borderTop: "1px solid #d3d1c7" },
  hint: { fontSize: 12, color: "#888780", marginTop: 10 },
  execLabel: { display: "inline-flex", alignItems: "center", gap: 6, fontSize: 13, color: "#5F5E5A", marginBottom: 10 },
  execInput: { width: 70, padding: "5px 8px", borderRadius: 6, border: "1px solid #d3d1c7", fontSize: 13 },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.4)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1000, padding: 20 },
  modal: { background: "#fff", borderRadius: 12, padding: 16, maxWidth: 720, width: "100%", maxHeight: "80vh", display: "flex", flexDirection: "column", gap: 10, boxShadow: "0 8px 32px rgba(0,0,0,0.15)" },
  modalHead: { display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: 15, fontWeight: 600 },
  modalTextarea: { flex: 1, minHeight: 320, padding: 10, fontFamily: "monospace", fontSize: 12, border: "1px solid #d3d1c7", borderRadius: 8, resize: "vertical" },
  modalActions: { display: "flex", gap: 8, justifyContent: "flex-end" },
} satisfies Record<string, CSSProperties>;
